#
# Makefile for SiI1292
#

obj-$(CONFIG_MHL_SII1292) = sii1292.o
sii1292-objs := sii1292_drv.o		\
		api/si_api1292.o	\
		api/si_regio.o		\
		cbus/si_apicbus.o	\
		cbus/si_regiocbus.o	\
		cec/si_apicec.o		\
		cec/si_apicpi.o		\
		edid/si_apiedid.o	\
		hal/si_hal.o		\
		hal/si_i2c.o		\
		main/si_cp1292.o	\
		main/si_cp1292_ext.o	\
		main/si_cpcbus.o	\
		main/si_cpcec.o		\
		msc/si_apimsc.o		\
		msc/si_apirap.o		\
		msc/si_apircp.o



