#                             
# Makefile for eFuse.         
#                             
                              
obj-$(CONFIG_EFUSE) += efuse_bch_8.o efuse_version.o efuse_hw.o efuse.o 
                              
obj-y += keys/core.o   keys/version3_extend.o                           
