obj-$(CONFIG_AM_LGS9XB1) += lgs9xb1_fe.o

lgs9xb1_fe-objs += LGS_USER.o  LGS_9X.o	LGS_HOOK.o	lgsfrontend.o
lgs9xb1_fe-objs += mxl5007/MxL5007.o
lgs9xb1_fe-objs += mxl5007/MxL5007_API.o
lgs9xb1_fe-objs += mxl5007/MxL_User_Define.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core


