#
# Makefile for the amlogic i2c bus drivers.
#

obj-y		+= aes_api.o
obj-y		+= aes_dec.o
obj-y		+= aes_enc.o
obj-y		+= aes_invsbox.o
obj-y		+= aes_sbox.o
obj-y		+= aes256_dec.o
obj-y		+= aes256_enc.o
obj-y		+= gf256mul.o

