#
# Makefile for the DVB driver.
#

obj-$(CONFIG_AM_DVB) += aml.o

aml-objs=aml_dvb.o aml_dmx.o aml_fe.o

obj-$(CONFIG_AM_CI) += amlci/

obj-$(CONFIG_AM_MXL101) += mxl101/

obj-$(CONFIG_AM_AVL6211) += avl6211/

obj-$(CONFIG_AM_M6_DEMOD) += DEMOD/

obj-$(CONFIG_AM_SI2176) += si2176/
obj-$(CONFIG_AM_SI2196) += si2196/
obj-$(CONFIG_AM_CTC703) += cresta/
